/RunAction/FileName group-25

# BF3 Source:
# Pos X box:
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 1 cm
/gps/pos/halfy 3.2 cm
/gps/pos/halfz 5 cm
/gps/pos/centre 7.65 0 0 cm
/gps/ang/type iso
/gps/energy 6.08e-1 MeV

# Neg X box:
/gps/source/add 1
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 1 cm
/gps/pos/halfy 3.2 cm
/gps/pos/halfz 5 cm
/gps/pos/centre -7.65 0 0 cm
/gps/ang/type iso 
/gps/energy 6.08e-1 MeV

# Pos Y box:
/gps/source/add 2.70
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 8.65 cm
/gps/pos/halfy 1 cm
/gps/pos/halfz 5 cm
/gps/pos/centre 0 4.2 0 cm
/gps/ang/type iso 
/gps/energy 6.08e-1 MeV

# Neg Y box:
/gps/source/add 2.70
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 8.65 cm
/gps/pos/halfy 1 cm
/gps/pos/halfz 5 cm
/gps/pos/centre 0 -4.2 0 cm
/gps/ang/type iso 
/gps/energy 6.08e-1 MeV

/run/beamOn 100000000